### PR TITLE
Lets try this

### PR DESCRIPTION
**Pull request by StochasticFactor**
I couldnt open project

### CODE REVIEW

**Comment by nekoni** [comment]
Can you open the project after this change?

**Comment by nekoni** [comment]
I've tried to delete my local copy and open again and it works for me, I user mac OS X and latest unity3d, 5.2.2f1

**Comment by alexvoro** [comment]
Who is Mr Random?

**Comment by nekoni** [comment]
Hahaha, he's the other Alex ;-)

**Comment by alexvoro** [comment]
Ok, I can get the assets, but nothing running, here is a screenshot. Is it
supposed to be like this?

[image: Inline image 1]

**Comment by nekoni** [comment]
I can't see the screenshot :-/

**Comment by alexvoro** [comment]
how about here?

**Comment by nekoni** [comment]
In the current version you should be able to move the player with the mouse + ASDW keys and shoot with right or left click. The targhet name is printed when hit.

**Comment by nekoni** [comment]
Btw, there are no visible characters, just 3 cubes and floors. Pretty basic atm.

**Pull request closed without merging**
